config/routes.rb
Hnotes::Application.routes.draw do
  resources :statistics
  devise_for :users, controllers: {sessions: 'sessions',registrations: 'registrations'}

=begin
  get "book/hide"
  get "book/move"
  get "frame/move"
  get "page/open"
  get "page/move"
  get "page/hide"
=end
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  resources :sessions
  

   root 'dashboard#index'

   resources :users
   resources :books
   resources :pages
   resources :frames

     
     
     resources :people do
         collection do
             get 'subscribe'
             get 'unsubscribe'
             get 'autocomplete'
             get 'search'
             get 'upload'
             post 'import'
         end
     end
     
     resources :frames do
         collection do
             get 'search'
             get 'export'
         end
         member do
             get 'show'
             post 'create'
             post 'update'
         end
      end
      

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    flash.clear
    @books = Book.all
  end

end

app/views/dashboard/index.html.slim
.fl.pt20
  h2 Dashboard
.clear0


.pt20
  h4 Actions
  
  ul.menu.clear0
    li.menu_item
      = link_to 'Search people', search_people_path
    li.menu_item
      = link_to 'Search text', search_frames_path

  .clear0
  
.pt20
  h4 Activity:

  .m20
    p
      - book = Book.last
      - if  book
        span
          strong Last updated book:
        span
          = link_to book.title, book, class: 'simple_link'
    p
      - frame = Frame.last
      - if frame
        span
          strong Last text fragment:
        span
          = link_to Frame.name, frame, class: 'fl simple_link'

    p
      - page = Page.last
      - if  page
        span
          strong Last updated page:
        span
          = link_to page.title, page, class: 'simple_link'

.pt20
  h4 Books
  .m20
    p
      = link_to "All books", books_path, class: 'fl simple_link'

 
.clear
.pt20
  h4 Help
  p
    | This application helps you to arrange database of hierarhical notes
    .pt10  Available categories:
    ul.p20
      li Admin
      li User
      li Visitor

     