config/routes.rb
Hnotes::Application.routes.draw do
  resources :statistics
  devise_for :users, controllers: {sessions: 'sessions',registrations: 'registrations'}

=begin
  get "book/hide"
  get "book/move"
  get "frame/move"
  get "page/open"
  get "page/move"
  get "page/hide"
=end
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  resources :sessions
  

   root 'dashboard#index'

   resources :users
   resources :books
   resources :pages
   resources :frames

     
     
     resources :people do
         collection do
             get 'subscribe'
             get 'unsubscribe'
             get 'autocomplete'
             get 'search'
             get 'upload'
             post 'import'
         end
     end
     
     resources :frames do
         collection do
             get 'search'
             get 'export'
         end
         member do
             get 'show'
             post 'create'
             post 'update'
         end
      end
      

end

app/models/concerns/person.rb
module Person
  extend ActiveSupport::Concern

    included do

      validates :password, :confirmation => true
      validates_length_of :password, :in => 6..20, :on => :create

      before_save :encrypt_password
      after_save :clear_password

      has_many :books, as: :person

      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # better to use gem ?
      validates :email, presence: true, :uniqueness => true, format: { with: VALID_EMAIL_REGEX }

      def have_access?(record)
          record.shared_to.include? self.id
      end

      def is_admin?
        false
      end
     
    end
end

app/controllers/people_controller.rb
#require 'will_paginate/array'


class PeopleController < ApplicationController

  skip_before_filter :authenticate, :only => :unsubscribe


  def index
    session[:people_sort_dir] = ['desc','asc'] if !session[:people_sort_dir]
    session[:people_sort_by] = params[:sort_by]
    psd =  session[:people_sort_dir]
    @sort_by = params[:sort_by] || 'master_id'
    if session[:people_sort_by] == params[:sort_by] # repeated click
      psd = psd.push(psd.shift) #cycle
    end
    @dir = psd[0]
    order_clause = "#{person_table(params[:people_category])}.#{@sort_by} #{@dir}"
    order_clause = "email_addresses.email #{@dir}" if @sort_by == 'email'
    @link = people_path
    options = {
      select: %w(master_id first_name last_name subscribed email_addresses.email),
      include: :email_addresses,
      conditions: search_conditions,
      order: order_clause
    }
    #options[:page] = params[:page] if params[:page]
    
    logger.debug "execute query, options: #{options}"
    if !params[:people_category]
      @people = people_scope.page(params[:page])   #paginate(options)
    else
      p = people_find(params[:people_category],options)
      #@people = p.paginate(:page => params[:page])  #paginate(options)
      #@people = p.page(params[:page])  #paginate(options)
      @people = Kaminari.paginate_array(p).page(params[:page])
      #logger.debug "## will_paginate people collection: #{@people.public_methods.sort}"
      #@people = p.page(params[:page])
      @category = params[:people_category]
    end
    
    if params[:commit]
      if @people.count > 0
        flash.now[:notice] = "Search results ( found #{@people.count} #{params[:people_category]}(s) )"
        #logger.debug "checking"
        #logger.debug "## #{@people.email_addresses.map(&:email)}"
      else
        flash.now[:error] = "Found nothing"
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @people }
    end
  end

  def show
    #logger.debug "## person_class: #{person_class.inspect}"
    #@person = people_scope.find_by_master_id(params[:id])
    @person = person_class.find_by_master_id(params[:id]) # ignore scope for now
    logger.debug "## person #{@person.inspect}"
    unless @person
      flash[:error] = "#{current_category} is not found"
      return redirect_to action: :index
    end
    @chart = person_chart(@person)
    respond_to do |format|
      format.html
      format.json { render json: @doctor }
    end
  end

  def autocomplete
    property = params[:property]
    if Segment::STATISTICS_PROPERTY_NAMES.include? property
      model_name = Campaign
      property = 'name'
    else
      model_name = person_class
    end
    values = model_name.all({
      select: property,
      group: property,
      conditions: ["#{property} LIKE ?", "#{params[:term]}%"],
      limit: 10
    }).map { |p| p.send property }
    render json: values
  end

  def search
    @person = person_class.new
  end

  def subscribe
    change_subscription(true, 'subscribed')
  end

  def unsubscribe
    change_subscription(false, 'unsubscribed')
  end

  def change_subscription(status, action_text)
    #@email = EmailAddress.find_by_email(params[:email])
    if @email.nil?
      flash.now[:error] = "Email address not found"
    else
      @person = @email.get_person #person_class.find_by_healthtap_id(@email.healthtap_id)
      if @person
        logger.debug @person.healthtap_id
        @person.subscribed = status
        @person.save
        flash.now[:notice] = "#{@person.first_name} #{@person.last_name} has been successfully #{action_text}."
      else
         flash.now[:error] = "Person not found"
      end
    end
    respond_to do |format|
      format.html {
       if current_user
         render :template => 'people/subscribe'
         return
       else
        render :template => 'people/subscribe', :layout => "public"
        return
       end
       }
      format.json { render json: { result: 'success', message: flash.now[:error] || flash.now[:notice] } }
    end
  end


  def upload
  end

  # import CSV data (emails) from uploaded file and unsubscribe people
  def import
    input = params[:file_form][:uploaded_data].instance_variable_get(:@tempfile)

    emails = input.read.split("\n").map { |s| s.strip.split(';')[0] }
    logger.debug "## initial content, entries count: #{emails.length}"
    emails = emails.compact.delete_if {|e| !e.include? '@'}.map{|e| (e) ? e.to_s.gsub(/[^\w\.\-\@\+\']+/,'') : ''}

    #ea = EmailAddress.where('email IN ("' + emails.join('","') + '")')
    logger.debug "## found #{ea.count} email addresses"
    ea.each do |e|
      p = e.get_person # according to tool current category
      p.update_attributes({:subscribed => false}) if p
    end

    unsubscribed_count = ea.count #people_to_unsubscribe.count  #Person.unsubscribe(emails)
    if unsubscribed_count > 0
      res = 'success'
      message = "Success. Number of unsubscribed: #{unsubscribed_count}"
    else
      res = 'failure'
      message = "Failed to read data from uploaded file"
    end
    respond_to do |format|
       format.json { render :json => {:result => res, :message => message} }
    end
  end


  private

  def person_class(cat=nil)
    { 'user' => User, 'admin' => Admin, 'guest' => Visitor}[cat || current_category]
  end

  def people_scope(cat=nil,options={})
    person_class(cat).by_hid #.order("#{person_class.table_name}.master_id desc")
  end


  def people_find(cat,options)
    logger.debug "## #{options[:conditions]}"
    options[:conditions][0] += " AND #{person_class(cat).by_hid_str}"
    person_class(cat).find(:all, options)
  end
  
  def person_table(cat=nil)
    pc = person_class(cat)
    pt = pc.to_s.downcase.pluralize
    pt
  end
  
  def search_conditions
    return unless params[:commit]
    conditions = []
    condition_params = []
    logger.debug "## person_class: #{person_class.to_s.downcase}"
    params[params[:people_category] || person_class.to_s.downcase].each do |k,v|
      unless v.blank?
        conditions << "#{k} LIKE ?"
        condition_params << "%#{v}%"
      end
    end
    unless params[:email].blank?
      conditions << "email_addresses.email LIKE ?"
      condition_params << "%#{params[:email]}%"
    end
    #conditions << "experts.healthtap_id > 10000001" if params[:category] == 'member'
    [conditions.join(' AND ')] + condition_params unless conditions.blank?
  end


end

app/views/people/index.html.slim
h2 Listing # (@category || current_category).pluralize.capitalize 

.p10.digg_pagination
  = paginate @people

/.m20{style: 'color: wheat'}
  /Sorted by: #{@sort_by} #{@dir}


table.listing
  tr
    th#master_id_col style: 'width: 8em' = link_to 'Master ID', @link + '?sort_by=master_id', title: 'click here to sort by Master ID'
    th style: 'width: 8em'  HealthTap ID
    th#first_name_col= link_to 'First Name', @link + '?sort_by=first_name', title: 'click here to sort by First Name'
    th#last_name_col= link_to 'Last Name', @link + '?sort_by=last_name', title: 'click here to sort by Last Name'
    / FIXME!!! - remove people in DB without assigned email address
    th#email_col= link_to 'Email', @link + '?sort_by=email', title: 'click here to sort by Email'
    - if params[:action] == 'index'
      th.error style: 'width: 8em'  Actions

  - @people.each do |person|
    - begin
      tr class=cycle('even','odd') 
        td= link_to person.master_id, person_path(person), class: 'simple_link'
        td= person.healthtap_id
        td
          - if person.first_name
            = link_to person.first_name, people_path + "?expert[first_name]=#{person.first_name}&commit=Search", title: "Search by first name", class: 'simple_link'
        td
          - if person.last_name
            = link_to person.last_name, people_path + "?expert[last_name]=#{person.last_name}&commit=Search", title:  "Search by last name", class: 'simple_link'
        td
          - logger.debug "tp"
          - person.email_addresses.each do |ea|
            .ml10= ea.email
        /= person.emails
        - if params[:action] == 'index'
          td= subscription_link(person)
    - rescue
      - logger.debug " bad person: #{person.to_json}"

br


.p10.digg_pagination
  = paginate @people


= render 'shared/display_sort_order'

app/views/people/search.slim
.clear10
h3 Fill at least one field to search for the person

= form_for @person, method: :get, url: { action: 'index' } do |f|
  - if @person.errors.any?
    #error_explanation
      h2= "# pluralize(@doctor.errors.count, "error")  prohibited this doctor from being saved:"
      ul
        - @person.errors.full_messages.each do |msg|
          li= msg

  .m20
    = f.label :first_name
    br
    = f.text_field :first_name
  .m20
    = f.label :last_name
    br
    = f.text_field :last_name
  .m20
    | E-mail
    br
    = text_field_tag :email
  .m20
    | Category
    =select_tag "people_category", options_for_select(%w(expert doctor member patient),['expert'])
  .m20
    = f.submit 'Search'

app/views/people/show.html.slim
.subnav
  = link_to "All #{current_category.pluralize}", people_path

h3 # current_category.capitalize} - #{@person.full_name} (subscribed: #{@person.subscribed? )

a name: "properties" 

.p10
  =link_to 'View statistics', '#statistics', class: 'simple_link'
  
.pl10

  h3 Properties
  table
    - @person.email_addresses.each do |ea|
      tr class=cycle('even','odd') 
        td Email
        td= ea.email
 
    - person_fields.each do |attr, value|
      - if value
        tr class=cycle('even','odd') 
          td
            = attr.humanize
          td
            = value
   
.pt20
  =link_to 'View properties', '#properties', class: 'simple_link'

= render "campaigns/chart"
    
.pl10
  a name: "statistics" 
  h3 Detailed statistics by campaign
  table.statistics
    tr
      th style=('width: 15em;')  Campaign
      th style=('width: 15em;')  Email
      th style=('width: 4em;')  Event
      th style=('width: 8em;')  Created at
    - @person.email_addresses.each do |ea|
      - if ea.statistics_items.first
        - ea.statistics_items.each do |si|
          tr class=cycle('even','odd') 
            - if si.campaign
              td= link_to si.campaign.name, campaign_path(si.campaign_id)
            - else
              td.error [ campaign deleted ]
            td= ea.email
            td= si.event
            td= si.created_at
      - else
        tr class=cycle('odd','even') 
          td colspan: 4, style: 'text-align: center'   [no entries]


.clear10

app/views/people/subscribe.slim
- if @person && current_user
  = link_to 'Back to person', person_path(@person)
- elsif current_user
  = link_to 'Back to people list', people_path

app/views/people/unsubscribe.slim
.m20
  = link_to 'All subscriptions', subscriptions_path, {:class => "menu p5"}

- if @subscription && @subscription.doctor
  h3 Subscription changed for # @subscription.doctor.full_name} having email #{@subscription.doctor.email 
- else
  .error
    | No subscription found for #{params[:email]}