config/routes.rb
Hnotes::Application.routes.draw do
  resources :statistics
  devise_for :users, controllers: {sessions: 'sessions',registrations: 'registrations'}

=begin
  get "book/hide"
  get "book/move"
  get "frame/move"
  get "page/open"
  get "page/move"
  get "page/hide"
=end
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  resources :sessions
  

   root 'dashboard#index'

   resources :users
   resources :books
   resources :pages
   resources :frames

     
     
     resources :people do
         collection do
             get 'subscribe'
             get 'unsubscribe'
             get 'autocomplete'
             get 'search'
             get 'upload'
             post 'import'
         end
     end
     
     resources :frames do
         collection do
             get 'search'
             get 'export'
         end
         member do
             get 'show'
             post 'create'
             post 'update'
         end
      end
      

end

app/views/shared/_display_sort_order.slim
javascript:
   $(document).ready(function() {
     var sort_by = "#{@sort_by}";
     sort_by = (sort_by.indexOf('_at') > 1) ? 'date' : sort_by;
     var it = '#{image_tag('sort_' + @dir + '.png', class: 'sort_dir')}';
     if (sort_by != '') {
       $('table.listing').find('th#' + sort_by + '_col a').append(it);
     }
   });

app/views/shared/_flashes.slim
.flash 
  - flash.each do |name, msg|
    .alert class="alert-#{name}"
      = msg
    
  

app/views/shared/_footer.slim
section#footer
  #footer_content.m0a
    .footer_column
      = link_to "Who We Are", 'http://www.hbook.com/who_we_are'
      = link_to 'What We Make', 'http://www.hbook.com/what_we_make'
      = link_to 'Work With Us', 'http://www.hbook.com/work_with_us'
    .footer_column
      = link_to 'Blog', 'http://blog.hbook.com/home', {:class => "mb5 blog"}
      = link_to 'Facebook', 'http://www.facebook.com/hbook', {:class => "mb5 facebook"}
      = link_to 'Twitter', 'http://www.facebook.com/Twitter', {:class => "twitter"}
    .footer_column
      = link_to "We're Hiring!", 'http://www.hbook.com/work_with_us/jobs'
      = link_to 'Press', 'http://www.hbook.com/who_we_are/press'
      = link_to 'Contact Us', 'http://www.hbook.com/pages/contact_us'
    .footer_column
      = link_to 'Terms of Use', 'http://www.hbook.com/pages/terms'
      = link_to 'Privacy & Security', 'http://www.hbook.com/pages/privacy_sharing'

app/views/shared/_header.slim
header#header.pt10
  #logo.fl
    .ml10
    .mt5
      | Env: #{Rails.env}
    .clear0
  nav.fr.pr10 id="top_menu"
    - if current_user
      .fl
        | Welcome #{current_user.email}
      .fl.ml20
        ul.menu
          li.menu_item
            = link_to 'Books', books_path
          li.menu_item
            = link_to 'Pages', pages_path
          li.menu_item
            = link_to 'Frames', frames_path

          .clear0
    - else
      ul.menu
        li.menu_item
          = link_to 'Log in', log_in_path
        li.menu_item
          = link_to 'Sign up', sign_up_path
  .clear0

app/views/shared/_upload.slim
#error_explanation.hidden

.p20
  = form_for :file_form, :url => {:controller => params[:controller], :action => :import}, :html => {:method => :post, :id => 'uploadForm', :remote=> true, :multipart => true} do |f|
    | Upload a file:
    = f.file_field :uploaded_data

= javascript_include_tag "ajax_file_upload.js"
= javascript_include_tag "jquery_form.js"
javascript:
  | $(function() {
    | $('#uploadForm').ajaxForm();
    | setAJAXSubmitOnChange('#uploadForm');
  | });