config/routes.rb
Hnotes::Application.routes.draw do
  resources :statistics
  devise_for :users, controllers: {sessions: 'sessions',registrations: 'registrations'}

=begin
  get "book/hide"
  get "book/move"
  get "frame/move"
  get "page/open"
  get "page/move"
  get "page/hide"
=end
  
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  resources :sessions
  

   root 'dashboard#index'

   resources :users
   resources :books
   resources :pages
   resources :frames

     
     
     resources :people do
         collection do
             get 'subscribe'
             get 'unsubscribe'
             get 'autocomplete'
             get 'search'
             get 'upload'
             post 'import'
         end
     end
     
     resources :frames do
         collection do
             get 'search'
             get 'export'
         end
         member do
             get 'show'
             post 'create'
             post 'update'
         end
      end
      

end

app/models/book.rb
class Book < ActiveRecord::Base

  #include UUID
  include Encryptable
  
  has_many :pages, :foreign_key => 'parent_id', as: :parent, class_name: 'Page', dependent: :destroy 
  belongs_to :person, polymorphic: true
  
  #scope :public, -> {where (hidden: false) }
  
  validates :title, presence: true, :uniqueness => true
 
  
  CATEGORIES = %w(private protected read-only public)

  # NOTE: book or node can be hidden (password protected display)
 
  def count_frames
    i =0
    self.pages.map {|page| i += page.frames.count}
    return i
  end
  
  def get_people_shared_to
    []
  end

  def pages_list
     self.pages.map(&:title).join(', ')
  end


  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_filter :set_current, only: [:show, :edit]
  before_action :set_book, only: [:show, :edit, :move, :hide]

  respond_to :html, :json
  
  # hack, to test response by typing URLs in browser
  layout -> (controller) { controller.request.format == 'json' ? false : 'application' }

  
  def index
      @books = Book.all.page(params[:page])
      @sort_by = 'updated_at'
      @dir = session[:books_sort_dir] || 'asc'
  end

  def move
  end

  def hide
  end

  def new
    @book = Book.new
  end

  def edit
    redirect_to action: :show
  end

  
  def create
      p params[:book].inspect
      @book = Book.new(book_params)
      if @book.save
          @message = flash[:success] = "#{@book.title} has been successfully created"
          @result = 'success'
          set_current
      else
          @message = flash[:danger] = "Form is invalid"
          @result = 'error'
      end
      respond_to do |format|
        format.html { redirect_to books_path }
        format.json { render template: 'books/show' }
      end
  end
  
  def show
    @message = ""
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    errors = @book.errors.full_messages
    if errors.empty?
        @message = flash[:success] = "#{@book.title} has been successfully updated"
        set_current
    else
        @message = flash[:danger] = "Form is invalid"
    end
    respond_to do |format|
      format.html { redirect_to books_path }
      format.json { render template: 'books/show'}
    end
  end
  
  private
  
  def book_params
      params.require(:book).permit(:title, :category, :id)
  end


  def set_book
    @book = Book.find(params[:id])
  end

  def set_current
      session[:current_node] = @book.id if @book
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_form.html.slim
= form_for @book do |f|
  -if @book.errors.any?
    #error_explanation
      h2= "#{pluralize(@book.errors.count, "error")}  prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |msg|
          li= msg

  .field.mt10
    = f.label :title
    = f.text_field :title, required: 'required', size: 64, :ng => {:model => "book.title"}
    span.error *
  .field.mt10
    = f.label :category
    = f.select :category, options_for_select(Book::CATEGORIES), class: 'category', title: 'Click to select category', :html => {"ng-model" => "book.category"}
  

  .mt10 Shared to: #{@book.get_people_shared_to || ''}
  .mt10 Number of pages / frames: #{@book.pages.count} / #{@book.count_frames}

  .mt20
    = f.submit 'Save', :ng => {:click => "updateBook()"}

app/views/books/edit.html.slim
.p10
  = link_to 'Back', books_path, {:class => "p5 menu"}
  | \|
  = link_to 'New', new_book_path, {:class => "p5 menu"}
  | \|
  = link_to 'Create New page', new_page_path, {:class => "menu p5"}

h2.p10 Editing book

= render 'form'

app/views/books/index.html.slim
- if !session[:use_reactjs]

  .subnav
    = link_to 'Create new book', new_book_path

  - if !@books.empty?
    .books
      h3.p20 Listing books
      .p10.digg_pagination
        = paginate @books
      table.listing
        tr
          th#id_col style=('width: 4em;') = link_to 'ID', books_path + '?sort_by=id', title: 'click here to sort by ID'
          th#title_col= link_to 'Title', books_path + '?sort_by=title', title: 'click here to sort by title'
          th style=('width: 7em;') 
          th#date_col style=('width: 4em;') 
            = link_to 'Date', books_path + '?sort_by=updated_at', title: 'click here to sort by date of modification'
        - @books.each do |book|
          tr class=cycle('even','odd') 
            td= link_to book.id, edit_book_path(book), class: 'simple_link'
            td= link_to book.title, edit_book_path(book), class: 'simple_link'
            td= book.pages.count
            td= book.updated_at
  - else
    .error.p20 No book found for current_user. Please create new one.

  .p10.digg_pagination
    = paginate @books

  = render 'shared/display_sort_order'

- else
  .books

app/views/books/new.html.slim
.subnav
  = link_to 'All books', books_path, {:class => "p5 menu"}

h2.p10 New book

= render 'form'

app/views/books/show.html.slim
.subnav
  = link_to 'All books', books_path, {:class => "menu p5"}
  = link_to 'Create new book', new_book_path, {:class => "menu p5"}
  = link_to 'Edit this book', edit_book_path(@book), {:class => "menu p5"}
  /!= link_to 'Export', output_fields_book_path(@book), {:class => "menu p5"}
  /!- if action == 'clone'
  /!  = link_to 'Save As New', copy_book_path(@book), {:class => "menu p5"}
  = link_to 'Delete book', @book, confirm: 'Are you sure?', method: :delete
  = link_to 'Create new page', new_page_path, {:class => "menu p5"}
  = link_to 'Back', books_path, {:class => "p5 menu"}
  .clear0


h2.p10 Editing book

.m20
  = render 'form'



- if @book.pages.count > 0

  table.listing.m20
    tr
      th#id_col style=('width: 4em;') = link_to 'ID', pages_path + '?sort_by=id', title: 'click here to sort by ID'
      th#title_col= link_to 'Title', pages_path + '?sort_by=title', title: 'click here to sort by title'
      th style=('width: 7em;') 
      th#date_col style=('width: 4em;') 
        = link_to 'Date', pages_path + '?sort_by=updated_at', title: 'click here to sort by date of modification'
    - @book.pages.each do |page|
      tr class=cycle('even','odd') 
        td= link_to page.id, edit_page_path(page), class: 'simple_link'
        td= link_to page.title, edit_page_path(page), class: 'simple_link'
        td= page.frames.count
        td= page.updated_at
        
  .tree-view ng-controller="treeCtrl"
    .tree-classic treecontrol="" tree-model="treedata" options="tree_options" on-selection="showSelected(node)" selected-node="node1" 
      | {{node.label}} ({{node.id}})
    